export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';
export const SINGLE_PRODUCT_LIST_REQUEST = 'SINGLE_PRODUCT_LIST_REQUEST';
export const SINGLE_PRODUCT_LIST_FAILURE = 'SINGLE_PRODUCT_LIST_FAILURE';
export const SINGLE_PRODUCT_LIST_SUCCESS = 'SINGLE_PRODUCT_LIST_SUCCESS';
